name: deploy
on:
  pull_request:
    branches:
      - main
  pull_request_target:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: push-notifications
        with:
          TYPE: Qmsg
          TITLE: push-notifications action
          DESP: | 
            This commit was made with the following details:
            - Commit ID: ${{ github.sha }}
            - Commit Message: ${{ github.event.head_commit.message }}
            - Run_id: ${{ github.run_id }}
            - Repository: ${{ github.repository }}
          QMSG_KEY: ${{ secrets.QMSG_KEY }}
          QMSG_QQ: ${{ secrets.QMSG_QQ }}
          QMSG_PUSH_TYPE: send
